import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* 必要に応じてメタタグを追加可能 */}
      </head>
      <body className={`${inter.className} bg-dark-2`}>
        <ClerkProvider
          appearance={{
            layout: {
              logoImageUrl: '/icons/yoom-logo.svg',
              socialButtonsVariant: 'iconButton',
            },
            variables: {
              colorText: "#fff",
              colorPrimary: '#0E78F9',
              colorBackground: '#1c1f2e',
              colorInputBackground: '#252a41',
              colorInputText: '#fff',
            },
          }}
          signInUrl="/sign-in"
          signUpUrl="/sign-up"
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}